### ISSUE TITLE
Add midori package

### ISSUE THREAD

**Issue by aniketstark** [termux/x11-packages#213] opened 2020-04-21 17:49 UTC
Midori browser

Midori is web browser

There is gui browser in for gui termux so i request to add this midori browser in termux-gui pacakges 

https://www.midori-browser.org/
Midori Browser

**Comment by xeffyr** [comment] 2020-04-21 17:59
Duplicate of https://github.com/termux/x11-packages/issues/37.

**Closed by xeffyr** 2020-04-21 17:59 UTC
