### ISSUE TITLE
Awesome wm

### ISSUE THREAD

**Issue by The-Dark-Phoenix** [termux/x11-packages#256] opened 2021-01-30 07:29 UTC
AwesomeWM is a dynamic window manager for the X Window System developed in the C and Lua programming languages. Lua is also used for configuring and extending the window manager. Its development began as a fork of dwm. It aims to be extremely small and fast, yet extensively customizable. It makes it possible for the user to manage windows with the use of keyboard. 

github: https://github.com/awesomeWM/awesome
homepage: https://awesomewm.org/

**Comment by WMCB-Tech** [comment] 2021-01-30 07:47
Duplicate of [#65](https://github.com/termux/x11-packages/issues/65)

**Closed** 2021-01-30 08:46 UTC
