### ISSUE TITLE
[Package]: openjfx

### ISSUE THREAD

**Issue by tempaccforissue** [termux/x11-packages#726] opened 2022-04-02 06:11 UTC
### Package description

“Rich client application platform for Java”

> OpenJFX or JavaFX is the latest GUI application development toolkit for the Java platform. JavaFX was included in the Java SE till JDK 8. Afterwards, to speed up its development, it was excluded from Java SE and open sourced as a standalone project: OpenJFX. Since then, it is developed separately but still under the management of Oracle.

> Java's other GUI toolkits, such as AWT and Swing are very old. Those have many limitations like not having support for modern UI/UX APIs, heavy memory footprint plus excessive resource usage. Here JavaFX comes as a replacement for those old toolkits. JavaFX provides many rich APIs which includes hardware acceleration, advanced 2D and 3D graphics, media and web support and so on.

> Now, as OpenJDK 17 is available on Termux as the `openjdk-17` package, it is right time to add OpenJFX as a package also. OpenJDK 17 can run OpenJFX 17 & 18 versions (OpenJDK N is compatible with OpenJFX N & N+1). It will be better to add OpenJFX 18 to Termux, if possible. Otherwise OpenJFX 17 will also be OK. Ubuntu and other popular Linux distributions provides OpenJFX by the name`openjfx`.

### Home page URL

https://openjfx.io

### Source code URL

https://github.com/openjdk/jfx

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/x11-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

The ‘linux’ SDK needs to be built, with all the modules included in it: `base`, `graphics`, `control`, `media`, `swing` and `web`. It provides the APIs for developing Desktop applications using JavaFX.

The `android` SDK needs not to be built, because it only provides the Android specific APIs for developing Android applications using JavaFX.

Trying to compile the `linux` SDK on device leads to many errors for my armv7l device.

**Comment by xtkoba** [comment] 2022-04-02 06:20
Duplicate of #727 (transferred from termux-packages).

**Closed by xtkoba** 2022-04-02 06:20 UTC
Labels: package request

**Comment by tempaccforissue** [comment] 2022-04-02 06:25
> Duplicate of #727 (transferred from termux-packages).

Please close that issue and reopen this issue, because the package is related to (and should be included into) the X11 packages.
