### ISSUE TITLE
Geany crashes with SIGSYS (Bad system call)

### ISSUE THREAD

**Issue by Auxilus** [termux/x11-packages#132] opened 2019-08-10 13:13 UTC
**Problem description**
Geany crashes with SUGSYS (Bad system call)

**System information**
System information:
Linux localhost 4.14.62-16393837 #1 SMP PREEMPT Fri Jul 19 15:09:48 KST 2019 aarch64 Android
Termux-packages arch:
aarch64
Android version:
9

**Comment by xeffyr** [comment] 2019-08-15 22:13
Caused by libcairo-x which attempts to use shm syscalls bypassing libandroid-shmem.

Fixed with https://github.com/termux/x11-packages/commit/0d0f516d5bab393d5c9be2e23e0c2706756d22e6. Updated package will be available soon.

**Closed by xeffyr** 2019-08-15 22:13 UTC
