### ISSUE TITLE
About kivy

### ISSUE THREAD

**Issue by T-Dynamos** [termux/x11-packages#638] opened 2022-03-13 12:22 UTC
![Screenshot_2022-03-13-17-49-25-125_com realvnc viewer android](https://user-images.githubusercontent.com/68729523/158059187-5676f218-6e8c-428c-9f53-8e575caf7944.jpg)
### Problem description

I successfully compiled kivy but unable to get window some error occurs

### What steps will reproduce the bug?

```
[CRITICAL] [Window      ] Unable to find any valuable Window provider. Please enable debug logging (e.g. add -d if running from the command line, or change the log level in the config) and re-run your app to identify potential causes
sdl2 - ImportError: dlopen failed: cannot locate symbol "XAllocClassHint" referenced by "/data/data/com.termux/files/usr/lib/python3.10/site-packages/kivy/graphics/cgl_backend/cgl_sdl2.cpython-310.so"
```

### What is the expected behavior?

It should work

### System information

termux-info:

```
Application version:
0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.org/apt/termux-main/ stable main
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.org/apt/termux-x11 x11 main
Updatable packages:
apt/stable 2.4.1-1 aarch64 [upgradable from: 2.4.1]
findutils/stable 4.9.0 aarch64 [upgradable from: 4.8.0]
freetype/stable 2.11.1 aarch64 [upgradable from: 2.11.0]
sdl2-image-static/x11 2.0.5-29 aarch64 [upgradable from: 2.0.5-28]
sdl2-image/x11 2.0.5-29 aarch64 [upgradable from: 2.0.5-28]
sdl2-mixer-static/x11 2.0.4-18 aarch64 [upgradable from: 2.0.4-17]
sdl2-mixer/x11 2.0.4-18 aarch64 [upgradable from: 2.0.4-17]
sdl2-net-static/x11 2.0.1-4 aarch64 [upgradable from: 2.0.1-3]
sdl2-net/x11 2.0.1-4 aarch64 [upgradable from: 2.0.1-3]
sdl2-ttf-static/x11 2.0.15-24 aarch64 [upgradable from: 2.0.15-23]
sdl2-ttf/x11 2.0.15-24 aarch64 [upgradable from: 2.0.15-23]
Android version:
7.0
Kernel build information:
Linux localhost 3.18.31-perf-g040a88f termux/termux-packages#1 SMP PREEMPT Thu Nov 7 00:28:25 WIB 2019 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
Redmi Note 4
```

**Comment by T-Dynamos** [comment] 2022-03-13 17:05
Add mtdev also in requirements it was also giving error of dlopen failed unable to locate libmtdev.so.1 when I installed mtdev in termux it makes so file libmtdev.so so i made a symbolic link with ln -s libmtdev.so to libmtdev.so.1 and it worked

**Comment by xtkoba** [comment] 2022-03-13 18:18
As for mtdev,

```patch
--- a/kivy/lib/mtdev.py
+++ b/kivy/lib/mtdev.py
@@ -27,7 +27,7 @@
 
 # load library
 if 'KIVY_DOC' not in os.environ:
-    libmtdev = cdll.LoadLibrary('libmtdev.so.1')
+    libmtdev = cdll.LoadLibrary('libmtdev.so')
 
 # from linux/input.h
 MTDEV_CODE_SLOT          = 0x2f  # MT slot being modified
```

**Comment by T-Dynamos** [comment] 2022-03-14 04:50
Are you done with it ? If not can I test it?

**Comment by xtkoba** [comment] 2022-03-14 09:49
You can test the artifacts in PR #637 and see what happens. Do not forget to uninstall pip-managed `kivy` before installing the deb package. The PR is marked as draft because it is not going to be merged unless `pip install kivy` on device is severely broken.

I cannot reproduce the `XAllocClassHint` issue. (Maybe some dependencies are missing?)

**Comment by T-Dynamos** [comment] 2022-03-14 12:44
In this build.sh [this](https://github.com/xtkoba/x11-packages/blob/kivy/packages/kivy/build.sh) you have set ldflags to something else that you have suggest me ??

**Comment by xtkoba** [comment] 2022-03-15 01:05
In reply to the former part: `-lpython3.10` is yet another workaround for android/ndk#201 that is necessary for building every Python extension. With cross building (or with current dependency) `-X11` is not needed thus "cannot reproduce."

In reply to the latter part: it is expected because `sdl2` package in our x11 repo is not configured with OpenGL (#624):

https://github.com/termux/x11-packages/blob/7a2a4536a0dd28fa1717e5dd01d5a06e4c3d7af0/packages/sdl2/build.sh#L34

These two parts are not much relevant to each other.

**Comment by T-Dynamos** [comment] 2022-03-15 03:08
So now I have to rebuild sdl2 with `--enable-video-oepngl`?

**Comment by xtkoba** [comment] 2022-03-16 08:36
You can test the artifacts in PR #639 and see what happens when combined with `mesa`.

**Comment by T-Dynamos** [comment] 2022-03-16 12:46
Works fine amd window work but gives error of cut buffer
```
[CRITICAL] [Cutbuffer   ] Unable to find any valuable Cutbuffer provider. Please enable debug logging (e.g. add -d if running from the command line, or change the log level in the config) and re-run your app to identify potential causes
xclip - FileNotFoundError: [Errno 2] No such file or directory: 'xclip'
```
And window crashes

**Comment by T-Dynamos** [comment] 2022-03-16 13:59
But `glxgears` works fine with huge fps 
![Screenshot_2022-03-16-19-27-41-650_com realvnc viewer android](https://user-images.githubusercontent.com/68729523/158606729-7c1296e3-8edd-4935-9608-72a724c732d7.jpg)

**Comment by Yisus7u7** [comment] 2022-03-16 14:04
> But `glxgears` works fine with huge fps ![Screenshot_2022-03-16-19-27-41-650_com realvnc viewer android](https://user-images.githubusercontent.com/68729523/158606729-7c1296e3-8edd-4935-9608-72a724c732d7.jpg) ![IMG_20220316_193131](https://user-images.githubusercontent.com/68729523/158607276-654298a4-8c11-4aac-87bd-c7196d37ddd6.jpg)

Well, this may happen only in arm32

**Comment by xtkoba** [comment] 2022-03-16 14:15
Not surprisingly.

**Comment by T-Dynamos** [comment] 2022-03-16 16:34
I suggest you to check kivy python for Android recipes 

https://github.com/kivy/python-for-android/tree/develop/pythonforandroid/recipes

**Comment by Grimler91** [comment] 2022-03-16 17:22
> Segmentation Fault in kivy

How do you know that the issue is in kivy and not in the project you are trying to run? Try running some minimal kivy example instead

> I suggest you to check kivy python for Android recipes
> 
> https://github.com/kivy/python-for-android/tree/develop/pythonforandroid/recipes

Not sure what we are suppose to "check" there

**Comment by xtkoba** [comment] 2022-03-16 17:28
Those recipes do not seem to be for Termux. Note that Termux is pretending not to be Androind in many situations. Building `sdl2` is one of them:

https://github.com/termux/x11-packages/blob/c3dd4344ab588c1e08d270d4b9aed5c73e7e5869/packages/sdl2/build.sh#L51-L55

**Comment by T-Dynamos** [comment] 2022-03-16 17:31
Ok I am trying but I even tried running kivy on proot-distro Ubuntu arm64 have same segmentation fault error , but same project on arm32 proot-distro Ubuntu works well and One thing more my project was working fine on android with buildozer (kivy) apk architecture 2qz armebi-v7a

**Comment by T-Dynamos** [comment] 2022-03-17 04:06
Fixed By fixing clock iteration error now its working fine and now when will be sdl2 with opengl and kivy support will be added officially in termux repo?

**Comment by xtkoba** [comment] 2022-03-17 10:59
@Yisus7u7 TL;DR:

```bash
export LD_PRELOAD="libandroid-shmem.so"
```

A little bit detail:

A basic thing that you should do when encounteing with "Bad system call" or similar is to `strace` the process.

With `strace`ing the `glxgears` process I get the following line in the trace log:

```
--- SIGSYS {si_signo=SIGSYS, si_code=SYS_SECCOMP, si_call_addr=0x797ede3430, si_syscall=__NR_shmget, si_arch=AUDIT_ARCH_AARCH64} ---
```

This reminded me of https://github.com/termux/termux-packages/issues/8162 immediately. If the process called the `shmget` function defined in `libandroid-shmem.so`, then the system call `shmget` would never be called.

If I opened an issue about this, I would give it the title as follows:

> [Bug]: `libandroid-shmem` not taking effect unless linked against main executable

**Comment by mguinhos** [comment] 2022-03-21 15:43
![Screenshot_20220321-122906_VNC Viewer.jpg](https://user-images.githubusercontent.com/43307018/159297289-373b9567-368c-4e30-8b47-68b78f6f4cf0.jpg)

Looks like it is also Segfaulting somewere after mesa's blend_general_float() function.
Due to an invalid memory acess.
Dont think there is something to do with kivymd itself.

**Comment by mguinhos** [comment] 2022-03-21 15:58
This is very interesting, becuase the previous mesa version was working well with kivymd.

**Comment by T-Dynamos** [comment] 2022-03-21 16:48
I think so kivymd uses pillow and there's problem with pillow

**Comment by mguinhos** [comment] 2022-03-21 16:58
```bash
export KIVY_GL_DEBUG=true
```

```
...
GL glBindTexture( target = 3553, texture = 16, )                            GL glTexParameteri( target = 3553, pname = 10241, param = 9729, )           GL glTexParameteri( target = 3553, pname = 10240, param = 9729, )           GL glTexParameteri( target = 3553, pname = 10242, param = 33071, )          GL glTexParameteri( target = 3553, pname = 10243, param = 33071, )          GL glPixelStorei( pname = 3317, param = 1, )                                GL glTexSubImage2D( target = 3553, level = 0, xoffset = 0, yoffset = 0, width = 29, height = 17, format = 6408, type = 5121, pixels*='0x7c1a664ed0', )  GL glGenTextures( n = 1, textures*='0x7a7321c25c', )                        GL glBindTexture( target = 3553, texture = 17, )                            GL glTexParameteri( target = 3553, pname = 10241, param = 9729, )           GL glTexParameteri( target = 3553, pname = 10240, param = 9729, )           GL glTexParameteri( target = 3553, pname = 10242, param = 33071, )          GL glTexParameteri( target = 3553, pname = 10243, param = 33071, )          GL glPixelStorei( pname = 3317, param = 4, )                                GL glTexImage2D( target = 3553, level = 0, internalformat = 6408, width = 4, height = 4, border = 0, format = 6408, type = 5121, pixels*='0x7a732034d0', )                                                                          GL glGenTextures( n = 1, textures*='0x7a7321c17c', )                        GL glBindTexture( target = 3553, texture = 18, )                            GL glTexParameteri( target = 3553, pname = 10241, param = 9729, )           GL glTexParameteri( target = 3553, pname = 10240, param = 9729, )           GL glTexParameteri( target = 3553, pname = 10242, param = 33071, )          GL glTexParameteri( target = 3553, pname = 10243, param = 33071, )          GL glPixelStorei( pname = 3317, param = 4, )                                GL glTexImage2D( target = 3553, level = 0, internalformat = 6408, width = 4, height = 4, border = 0, format = 6408, type = 5121, pixels*='0x7a732035b0',
 )
GL glDeleteTextures( n = 2, textures*='0x7a7a4b5b00', )                     GL glClearColor( red = 0.9803921580314636, green = 0.9803921580314636, blue = 0.9803921580314636, alpha = 1.0, )                                        GL glClear( mask = 17664, )                                                 GL glUseProgram( program = 1, )                                             GL glUniform1f( location = 3, x = 1.0, )                                    GL glUniform1i( location = 4, x = 0, )                                      GL glUniform4f( location = 2, x = 1.0, y = 1.0, z = 1.0, w = 1.0, )         GL glUniformMatrix4fv( location = 1, count = 1, transpose = 0, value*='0x7fee1bb030', )                                                                 GL glUniformMatrix4fv( location = 0, count = 1, transpose = 0, value*='0x7fe
e1bb030', )                                                                 GL glGetUniformLocation( program = 1, name*=b'frag_modelview_mat', )        GL glGetIntegerv( pname = 35725, params*='0x7fee1bab34', )
GL glUniformMatrix4fv( location = 0, count = 1, transpose = 0, value*='0x7fe
e1ba9f0', )                                                                 GL glGetIntegerv( pname = 35725, params*='0x7fee1baad4', )
```

Got a call trace, with the KIVY_GL_DEBUG environment variable, this is the last calls before crashing

**Comment by mguinhos** [comment] 2022-03-21 16:58
```bash
export KIVY_GL_DEBUG=true
```

```
...
GL glBindTexture( target = 3553, texture = 16, )                            GL glTexParameteri( target = 3553, pname = 10241, param = 9729, )           GL glTexParameteri( target = 3553, pname = 10240, param = 9729, )           GL glTexParameteri( target = 3553, pname = 10242, param = 33071, )          GL glTexParameteri( target = 3553, pname = 10243, param = 33071, )          GL glPixelStorei( pname = 3317, param = 1, )                                GL glTexSubImage2D( target = 3553, level = 0, xoffset = 0, yoffset = 0, width = 29, height = 17, format = 6408, type = 5121, pixels*='0x7c1a664ed0', )  GL glGenTextures( n = 1, textures*='0x7a7321c25c', )                        GL glBindTexture( target = 3553, texture = 17, )                            GL glTexParameteri( target = 3553, pname = 10241, param = 9729, )           GL glTexParameteri( target = 3553, pname = 10240, param = 9729, )           GL glTexParameteri( target = 3553, pname = 10242, param = 33071, )          GL glTexParameteri( target = 3553, pname = 10243, param = 33071, )          GL glPixelStorei( pname = 3317, param = 4, )                                GL glTexImage2D( target = 3553, level = 0, internalformat = 6408, width = 4, height = 4, border = 0, format = 6408, type = 5121, pixels*='0x7a732034d0', )                                                                          GL glGenTextures( n = 1, textures*='0x7a7321c17c', )                        GL glBindTexture( target = 3553, texture = 18, )                            GL glTexParameteri( target = 3553, pname = 10241, param = 9729, )           GL glTexParameteri( target = 3553, pname = 10240, param = 9729, )           GL glTexParameteri( target = 3553, pname = 10242, param = 33071, )          GL glTexParameteri( target = 3553, pname = 10243, param = 33071, )          GL glPixelStorei( pname = 3317, param = 4, )                                GL glTexImage2D( target = 3553, level = 0, internalformat = 6408, width = 4, height = 4, border = 0, format = 6408, type = 5121, pixels*='0x7a732035b0',
 )
GL glDeleteTextures( n = 2, textures*='0x7a7a4b5b00', )                     GL glClearColor( red = 0.9803921580314636, green = 0.9803921580314636, blue = 0.9803921580314636, alpha = 1.0, )                                        GL glClear( mask = 17664, )                                                 GL glUseProgram( program = 1, )                                             GL glUniform1f( location = 3, x = 1.0, )                                    GL glUniform1i( location = 4, x = 0, )                                      GL glUniform4f( location = 2, x = 1.0, y = 1.0, z = 1.0, w = 1.0, )         GL glUniformMatrix4fv( location = 1, count = 1, transpose = 0, value*='0x7fee1bb030', )                                                                 GL glUniformMatrix4fv( location = 0, count = 1, transpose = 0, value*='0x7fe
e1bb030', )                                                                 GL glGetUniformLocation( program = 1, name*=b'frag_modelview_mat', )        GL glGetIntegerv( pname = 35725, params*='0x7fee1bab34', )
GL glUniformMatrix4fv( location = 0, count = 1, transpose = 0, value*='0x7fe
e1ba9f0', )                                                                 GL glGetIntegerv( pname = 35725, params*='0x7fee1baad4', )
```

Got a call trace, with the KIVY_GL_DEBUG environment variable, this is the last calls before crashing

**Comment by mguinhos** [comment] 2022-03-21 17:12
But, Dont worry, this will be solved soon! Kivy is almost working!

**Comment by xtkoba** [comment] 2022-03-30 16:51
Ah, I almost forgot this. Would you please open a new issue for the `mesa` crash? As discussed above, it seems to be independent of `kivy`. If possible, please provide a reproducing example that does not use `kivy`. Thanks.

**Closed** 2022-04-07 08:17 UTC
Labels: enhancement, python

**Comment by T-DynamosFans** [comment] 2022-04-09 06:00
Couldn't believe on my eyes . i am @T-Dynamos 
![Screenshot_2022-04-09-11-25-38-164_com realvnc viewer android](https://user-images.githubusercontent.com/96837234/162558735-b19c7e8f-8d83-43a1-ac47-679136e89d6a.jpg)
![Screenshot_2022-04-09-11-16-58-278_com realvnc viewer android](https://user-images.githubusercontent.com/96837234/162558738-02ccdcb0-aa28-484b-9f0b-2c2248228dab.jpg)
termux-info
```
Application version:
0.117
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.org/apt/termux-main stable main
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.org/apt/termux-x11 x11 main
Updatable packages:
apt/stable 2.4.1-2 arm [upgradable from: 2.3.6]
bash/stable 5.1.16-1 arm [upgradable from: 5.1.16]
curl/stable 7.82.0-1 arm [upgradable from: 7.82.0]
gzip/stable 1.12 arm [upgradable from: 1.11-3]
libcap-ng/stable 2:0.8.3 arm [upgradable from: 1:0.8.3-pre1-0]
libcurl/stable 7.82.0-1 arm [upgradable from: 7.82.0]
libexpat/stable 2.4.8 arm [upgradable from: 2.4.7]
libgcrypt/stable 1.10.1 arm [upgradable from: 1.9.4]
libsqlite/stable 3.38.2 arm [upgradable from: 3.38.1]
perl/stable 5.34.1-1 arm [upgradable from: 5.34.1]
termux-keyring/stable 3.1 all [upgradable from: 3.0]
termux-tools/stable 0.173 all [upgradable from: 0.168]
unbound/stable 1.15.0 arm [upgradable from: 1.13.2-3]
util-linux/stable 2.38 arm [upgradable from: 2.37.4]
zlib/stable 1.2.12 arm [upgradable from: 1.2.11-5]
Android version:
10
Kernel build information:
Linux localhost 4.9.190-perf-gba91b47 #1 SMP PREEMPT Tue Mar 8 15:43:19 CST 2022 armv8l Android
Device manufacturer:
Xiaomi
Device model:
M2006C3MII
```
Working on arm .  I used master branch of kivymd
`pip3 install https://github.com/kivymd/KivyMD/archive/refs/heads/master.zip`
Can you please include steps on Termux wiki to instl kivy?

**Comment by T-DynamosFans** [comment] 2022-04-09 06:25
![Screenshot_2022-04-09-11-53-33-579_com realvnc viewer android](https://user-images.githubusercontent.com/96837234/162559531-a50716c3-f771-4cb4-bde5-41564c1adc93.jpg)
![Screenshot_2022-04-09-11-52-38-196_com realvnc viewer android](https://user-images.githubusercontent.com/96837234/162559535-20d63f4a-5c89-4914-8602-30f2046cc2ec.jpg)
But fps are too low like 2fps

**Comment by Yisus7u7** [comment] 2022-04-09 06:34
@T-Dynamos 

```bash
apt install gl4es

LD_LIBRARY_PATH=$PREFIX/lib/gl4es ./app.py

```

**Comment by T-DynamosFans** [comment] 2022-04-09 06:52
For graphics drivers?

**Comment by T-DynamosFans** [comment] 2022-04-09 06:54
And what does it means ?
```
Mesa: User error: GL_INVALID_OPERATION in glUniform1("t"@2 is float, not int)
Mesa: User error: GL_INVALID_OPERATION in glUniform1("t"@2 is float, not int)
```

**Comment by T-DynamosFans** [comment] 2022-04-09 06:55
> > For graphics drivers?
> 
> Yes

I don't get it . Can yu explain?

**Comment by Yisus7u7** [comment] 2022-04-09 07:16
![Screenshot_20220409-021527](https://user-images.githubusercontent.com/64093255/162561231-bbfd04d1-815c-4dc3-a30f-c5f9de7861ff.png)

Yes, works slow...

**Comment by T-DynamosFans** [comment] 2022-04-09 07:31
Ok let's try it on arm64 till then you can try with fps monitoring and these examples https://github.com/HeaTTheatR/Articles

**Comment by T-DynamosFans** [comment] 2022-04-09 13:13
![Screenshot_2022-04-09-18-11-53-516_com realvnc viewer android](https://user-images.githubusercontent.com/96837234/162575567-1a29090f-a766-4c30-8e6f-e56b86b16a92.jpg)
Termux-info
```
Application version:
0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.org/apt/termux-main stable main
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.org/apt/termux-x11 x11 main
# root-repo (sources.list.d/root.list)
deb https://packages.termux.org/apt/termux-root root stable
# sources.list.d/termux-desktop-xfce.list
deb [trusted=yes arch=all] https://Yisus7u7.github.io/termux-desktop-xfce/packages desktop-xfce extras
Updatable packages:
All packages up to date
Android version:
7.0
Kernel build information:
Linux localhost 3.18.31-perf-g040a88f #1 SMP PREEMPT Thu Nov 7 00:28:25 WIB 2019 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
Redmi Note 4
```
Its confirmed that issue is only on `arm64`  and simple kivy programs work with same slow speed as `arm`

**Comment by T-DynamosFans** [comment] 2022-04-09 13:16
@xtkoba 
Please add arm64 tag
