### ISSUE TITLE
[Bug]: [Bug]: xfce4-panel: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.xfce.Panel was not provided by any .service files

### ISSUE THREAD

**Issue by ivam3** [termux/x11-packages#539] opened 2021-12-16 14:14 UTC
### Problem description

during the glib update its warnings were shown and after that it shows an error when executing xfce4-session when obtaining the bus connection and in wayland it does not show the toolbar and the terminal does not run. And when downgrading glib glib-bin and gstreamer doesn't run xfce4-sessions in wayland.
![Screenshot_20211216-042523_Termux](https://user-images.githubusercontent.com/27752315/146387373-2b92628b-37b0-46d1-ba9a-86c8360dcc3c.jpg)
![Screenshot_20211216-074406_Termux](https://user-images.githubusercontent.com/27752315/146387444-fdcce129-da6c-40bb-ba7b-682cafb6c146.jpg)
![Screenshot_20211216-072410_TermuxWayland](https://user-images.githubusercontent.com/27752315/146387475-9f8505bf-3609-483b-be1d-b043d635b9cc.jpg)
![Screenshot_20211216-183153_Termux](https://user-images.githubusercontent.com/27752315/146469502-a449d695-99c5-4154-8f0c-c296771e73ab.jpg)

### What steps will reproduce the bug?

apt install glib
export XDG_RUNTIME_DIR=$TMPDIR
termux-x11 :0 >/dev/null 2>/dev/null
env DISPLAY=:0 xfce4-session

### System information

termux-info:

```

```
Application version:
0.117
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.librehat.com/apt/termux-main/ stable main
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
# sources.list.d/abhacker.repo.list
deb [arch=all,aarch64] https://abhackerofficial.github.io/abhacker.repo/ abhacker main
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.org/apt/termux-x11 x11 main
# root-repo (sources.list.d/root.list)
deb https://packages.termux.org/apt/termux-root root stable
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
Updatable packages:
mutt/stable 2.1.4-3 aarch64 [upgradable from: 2.1.1-3]
youtubedr/stable 2.7.6 aarch64 [upgradable from: 2.7.5]
Android version:
11
Kernel build information:
Linux localhost 4.4.177-22602103 #1 SMP PREEMPT Fri Oct 15 00:57:06 KST 2021 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-A305G

**Comment by Yisus7u7** [comment] 2021-12-16 16:49
Update your packages, xfce4-session works fine, currently the severity error is libvte.

**Comment by xtkoba** [comment] 2021-12-16 18:22
I suppose that the problem specifically described in the current title was a transient one, and should not be caused by the combination of `pango 1.48.7-1` and `glib 2.70.2-1` (for aarch64):

```
$ readelf -Wa lib/libpango-1.0.so | grep NEEDED
 0x0000000000000001 (NEEDED)             Shared library: [libm.so]
 0x0000000000000001 (NEEDED)             Shared library: [libglib-2.0.so]
 0x0000000000000001 (NEEDED)             Shared library: [libgobject-2.0.so]
 0x0000000000000001 (NEEDED)             Shared library: [libgio-2.0.so]
 0x0000000000000001 (NEEDED)             Shared library: [libfribidi.so]
 0x0000000000000001 (NEEDED)             Shared library: [libharfbuzz.so]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so]

$ readelf -Wa lib/libglib-2.0.so | grep g_memdup2
   668: 00000000000ec170    76 FUNC    GLOBAL DEFAULT   12 g_memdup2
```

And the rest seems to be a duplicate of #537.

**Comment by ivam3** [comment] 2021-12-17 00:04
@Yisus7u7 obviously there're all packages up to date

**Comment by xtkoba** [comment] 2021-12-17 00:30
Please set an appropriate title for the issue, something like:

```
[Bug]: xfce4-panel: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.xfce.Panel was not provided by any .service files
```

**Comment by ivam3** [comment] 2021-12-17 00:49
@xtkoba thanks for answering. I understand that it is only a warning but I thought it necessary to mention it, and I already modified the title of the problem. For now I still can't find a solution

**Comment by xtkoba** [comment] 2021-12-17 01:22
As for `xfce4-panel` there are similar cases in the wild, one of which is https://forum.manjaro.org/t/70855/.

**Comment by Yisus7u7** [comment] 2021-12-17 02:58
> @xtkoba thanks for answering. I understand that it is only a warning but I thought it necessary to mention it, and I already modified the title of the problem. For now I still can't find a solution

Ah provado reinstall termux? Many of these cases are usually because people damage their environments. 

I've just tested on aarch64 devices and xfce4-session works.

**Comment by ivam3** [comment] 2021-12-17 03:09
Well, the toolbar returned to the screen ... I had to configure the execution of xfce4-panel in applications -> settings -> session & startup with flag --display=:0 :
![Screenshot_20211216-205637_TermuxWayland](https://user-images.githubusercontent.com/27752315/146482551-bdf83cbc-7043-4d5f-a256-b7d63ee7be5b.jpg)
![Screenshot_20211216-210006_TermuxWayland](https://user-images.githubusercontent.com/27752315/146482583-3fd4396a-3602-42a9-8a44-9c72768f4dd4.jpg)

**Comment by Yisus7u7** [comment] 2021-12-17 03:20
> Bueno, la barra de herramientas volvió a la pantalla ... Tuve que configurar la ejecución de xfce4-panel en aplicaciones -> configuración -> sesión e inicio con bandera --display =: 0: ![Screenshot_20211216-205637_TermuxWayland](https://user-images.githubusercontent.com/27752315/146482551-bdf83cbc-7043-4d5f-a256-b7d63ee7be5b.jpg) ![Screenshot_20211216-210006_TermuxWayland](https://user-images.githubusercontent.com/27752315/146482583-3fd4396a-3602-42a9-8a44-9c72768f4dd4.jpg)

that confirms what I thought, the session was broken, that's why I recommend that when you go to close x11, close all applications and exit the xfce session (in the logout option), if you do an unexpected close it is very likely let xfce break, in that case remove the contents of ˋ$HOME/.config/xfceˋ

**Comment by Yisus7u7** [comment] 2021-12-17 03:22
that confirms what I thought, the session was broken, that's why I recommend that when you go to close x11, close all applications and exit the xfce session (in the logout option), if you do an unexpected close it is very likely let xfce break, in that case remove the contents of **$HOME/.config/xfce**

**Comment by ivam3** [comment] 2021-12-17 03:40
@Yisus7u7  I have eliminated the $ PREFIX tree, however the problem persists ... BTW, thank u @xtkoba for now I have solved the panel problem but I still have the terminal problem pending, because it still does not open xfce4-terminal, tmate or fish. Those  just flashed :

Uploading Edited_20211216_212413.mp4…

**Comment by ivam3** [comment] 2021-12-17 03:49
@Yisus7u7 I always close the season on the rugth way (clicking on user name-->logout) btw i was removed $PREFIX, hidden config files in $HOME and reinstall all packages , anyway i had to set xfce4-panel on startup setting but the terminal continues crashed

**Comment by Yisus7u7** [comment] 2021-12-17 03:51
@ivam3 problem solved in #540 

![Screenshot_20211216-225030](https://user-images.githubusercontent.com/64093255/146486077-9ce50811-6643-4604-b2b7-90940dbedafc.png)

wait for the update or download the artifacts at the link below

https://github.com/termux/x11-packages/actions/runs/1590272313

**Comment by Yisus7u7** [comment] 2021-12-17 04:04
The pango package needs to be updated, then I check that..

**Closed** 2021-12-20 14:32 UTC
Labels: bug report

**Comment by ivam3** [comment] 2021-12-22 02:23
The issue was resolved downgrading the library's libvte, for a while until it will be patched we can get it from link below
