### ISSUE TITLE
AzPainter cannot find libandroid-shmem.so

### ISSUE THREAD

**Issue by cargocultprog** [termux/x11-packages#220] opened 2020-06-05 16:09 UTC
**Problem description**

Using xfce4 desktop. The desktop works. Programs Netsurf, Thunar, mtpainter and others work. 
But azpainter cannot launch. Terminal:

CANNOT LINK EXECUTABLE "azpainter": library "libandroid-shmem.so" not found

I believe that azpainter was working a month ago. Could this new problem be caused by recent (early June 2020) updates to xfce4, exo, and others?

Any attempt to launch azpainter, from menu or command. Repeatable.

**Expected behavior**

AzPainter window should open on xfce4 desktop. Using VNC Viewer.

**System information**

Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://termux.org/packages/ stable main
# x11-repo (sources.list.d/x11.list)
deb https://dl.bintray.com/xeffyr/x11-packages x11 main
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
Updatable packages:
All packages up to date
Android version:
9
Kernel build information:
Linux localhost 4.4.111-17420370 #1 SMP PREEMPT Mon Mar 2 15:38:05 KST 2020 armv8l Android
Device manufacturer:
samsung
Device model:
SM-T510

**Comment by xeffyr** [comment] 2020-06-05 16:12
> Could this new problem be caused by recent (early June 2020) updates to xfce4, exo, and others?

Caused by azpainter update likely. It has changed build system recently, moved from autotools to something selfwritten, so I guess just LDFLAGS (which set DT_RUNPATH) were not applied.

**Comment by xeffyr** [comment] 2020-06-05 16:57
Fixed in `azpainter 1:2.1.6-6`, `pkg upgrade`.

**Closed by xeffyr** 2020-06-05 16:57 UTC
Labels: bug
