### ISSUE TITLE
After recently pkg update, otter-browser cannot be opened anymore

### ISSUE THREAD

**Issue by mazhe1988** [termux/x11-packages#489] opened 2021-11-03 23:36 UTC
### Problem description

After run pkg update, otter-browser cannot be opened anymore.

### What steps will reproduce the bug?

~ $ otter-browser
CANNOT LINK EXECUTABLE "otter-browser": library "libicuuc.so.69" not found: needed by /data/data/com.termux/files/usr/lib/libQt5WebKit.so in namespace (default)

### System information

termux-info:

```
Application version:
0.117
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.librehat.com/apt/termux-main/ stable main
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.org/apt/termux-x11 x11 main
# root-repo (sources.list.d/root.list)
deb https://packages.termux.org/apt/termux-root root stable
Updatable packages:
All packages up to date
Android version:
11
Kernel build information:
Linux Pixel-2-XL 4.4.283-lineage-gb72b369040eb #1 SMP PREEMPT Thu Oct 14 09:57:09 UTC 2021 aarch64 Android
Device manufacturer:
Google
Device model:
Pixel 2 XL
```

**Comment by xeffyr** [comment] 2021-11-04 14:25
Will be available once https://github.com/termux/x11-packages/pull/480 get merged.

**Comment by junrenshi** [comment] 2021-11-13 00:13
The problem is due to an incompatible version of libicuuc.so.  I can only find libicuuc.so.70 in the lib directory.

**Comment by mazhe1988** [comment] 2021-11-13 05:01
I saw the new update from otter-browser and qtwebkit, but right now otter-browser still cannot run after update. Is this been solved or not?

**Closed** 2021-11-13 09:35 UTC

**Comment by xeffyr** [comment] 2021-11-13 09:36
> but right now otter-browser still cannot run after update

It doesn't show linker error at least. Not sure about any possible runtime issues. Upgrade all packages.

**Comment by junrenshi** [comment] 2021-11-13 10:12
No, it is not working.  The arch is aarch64.   The qtwebkit for the arch was released on Oct 26, and is linked to libicu-69.  The current version of libicu is 70.
