### ISSUE TITLE
Geany plugins

### ISSUE THREAD

**Issue by Yisus7u7** [termux/x11-packages#268] opened 2021-03-05 01:00 UTC
If and tried to compile it, it gives paths error

**Package description**

Geany plugins is the plugin manager for the Geany ide

**Link to home page and sources**
1. Home page:
https://plugins.geany.org/
2. Source code:
https://github.com/geany/geany-plugins

**Comment by WMCB-Tech** [comment] 2021-03-05 01:03
I think there's already an issue about geany plugins

https://github.com/termux/x11-packages/issues/199

**Comment by Yisus7u7** [comment] 2021-03-05 01:06
Hmm yes, but this package would be very useful, it would greatly increase the usefulness of Geany's ide
![Screenshot_20210304-111011](https://user-images.githubusercontent.com/64093255/110052127-0a991a80-7d25-11eb-847e-93e0967ce4b3.png)

**Comment by Grimler91** [comment] 2021-03-05 05:02
Duplicate of #199

**Closed by Grimler91** 2021-03-05 05:02 UTC
